[workspace]
members = [
  "compiler",
  "compiler/frontend",
  "compiler/backend",

  "runtime",

  "tools/javapv",

  "crates/strbuf",
  "crates/classfile",
  "crates/jar",
  "crates/llvm"
]

[profile.release]
lto = true
