[package]
name = "runtime"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
edition = "2018"

[lib]
name = "runtime"
crate-type = ["staticlib"]

[dependencies]
backtrace = "0.3.13"
libc = "0.2.43"
