[package]
name = "classfile"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
byteorder = "1.2.6"
bytes = "0.4.10"
cesu8 = "1.1.0"
failure = "0.1.2"
log = "0.4.6"
string = "0.1.1"
