[package]
name = "javapv"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
failure = "0.1.2"
md5 = "0.4.0"
structopt = "0.2.11"

[dependencies.classfile]
path = "../../crates/classfile"
