[package]
name = "llvm"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
edition = "2018"

[dependencies]
libc = "0.2.43"
llvm-sys = { version = "70.0.2", features = ["no-llvm-linking"] }

[build-dependencies]
cc = "1.0.26"
