[package]
name = "jar"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
edition = "2018"

[dependencies]
bytes = "0.4.10"
failure = "0.1.2"
zip = { git = "https://github.com/srijs/zip-rs.git", rev = "5d5491d" }

[dependencies.classfile]
path = "../classfile"
