[package]
name = "jar"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
workspace = "../.."

[dependencies]
failure = "0.1.2"
zip = "0.4.2"

[dependencies.classfile]
path = "../classfile"
