[package]
name = "jar"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]
workspace = "../.."

[dependencies]
bytes = "0.4.10"
failure = "0.1.2"

[dependencies.classfile]
path = "../classfile"

[dependencies.zip]
git = "https://github.com/srijs/zip-rs.git"
rev = "be6847a"
